const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 20,
      brand: "Nike",
      rating: 2.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 76,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 32,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 34,
      countInStock: 1,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 9,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 124,
      countInStock: 0,
      brand: "Nike",
      rating: 5,
      numReviews: 3,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 56,
      countInStock: 3,
      brand: "Puma",
      rating: 1,
      numReviews: 4,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Slim Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 59,
      countInStock: 10,
      brand: "Adidas",
      rating: 2,
      numReviews: 12,
      description: "high quality product",
    },
  ],
};

export default data;
